from dataclasses import dataclass


@dataclass
class BackendState:
    ...

class Backend:
    def __init__(self, config): ...

    def simulation_init(self): ...

    def next_step(self): ...

    def previous_step(self): ...

    def start(self): ...

    def set_config(self, config): ...

    def spawn_entites(self): ...

    def stop(self): ...
