[tool.poetry]
name = "2d-simulation"
version = "0.1.0"
description = ""
authors = ["alex <melnikov1991@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
